#生产环境配置:通过application.yml添加不同的后缀来区分,只有生产环境才会加载这个配置
#先区分多环境：前端区分开发和线上接口，后端prod改为用线上公网可访问的数据库
spring:
  #数据库的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxx
    username: root
    password: xxxxxx
